# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Reservation(BaseModel):
    guestCurrency: str
    confirmationCode: str
    isBringingPets: bool
    guestProfileUrl: str
    numberOfGuests: int
    hostRespondeAt: str | None = None
    numberOfInfants: int
    createdAt: str
    hostingUrl: str
    guestVatCountry: str
    numberOfChildren: int
    numberOfAdults: int
    numberOfPets: int
    nights: int
    hostProfileUrl: str
    startDate: str
    status: str
    updatedAt: str
    message: str | None = None
    canceledAt: str | None = None


class Model(BaseModel):
    bookingSessions: list[dict[str, Any]]
    reservations: list[Reservation]
