# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T16:11:03+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Author(BaseModel):
    role: str
    name: str | None
    metadata: dict[str, Any]


class Thought(BaseModel):
    chunks: list[Any]
    content: str
    finished: bool
    summary: str


class Content(BaseModel):
    content_type: str
    parts: list[str | dict[str, Any]] | None = None
    language: str | None = None
    response_format_name: Any | None = None
    text: str | None = None
    assets: list[Any] | None = None
    result: str | None = None
    summary: str | None = None
    tether_id: Any | None = None
    domain: str | None = None
    title: str | None = None
    url: str | None = None
    name: str | None = None
    crawl_date: Any | None = None
    crawl_timestamp: Any | None = None
    pub_date: Any | None = None
    pub_timestamp: float | None = None
    ref_id: str | None = None
    snippet: str | None = None
    source_analysis_msg_id: str | None = None
    thoughts: list[Thought] | None = None
    content: str | None = None


class Message(BaseModel):
    id: str
    author: Author
    create_time: float | None
    update_time: float | None
    content: Content
    status: str
    end_turn: bool | None
    weight: float
    metadata: dict[str, Any]
    recipient: str
    channel: str | None


class Mapping(BaseModel):
    id: str
    message: Message | None = None
    parent: str | None
    children: list[str]


class Model(BaseModel):
    title: str | None = None
    create_time: float | None = None
    update_time: float | None = None
    moderation_results: list[Any] | None = None
    current_node: str | None = None
    plugin_ids: Any | None = None
    conversation_id: str | None = None
    conversation_template_id: str | None = None
    gizmo_id: str | None = None
    gizmo_type: str | None = None
    is_archived: bool | None = None
    is_starred: Any | None = None
    safe_urls: list[str] | None = None
    blocked_urls: list[Any] | None = None
    default_model_slug: str | None = None
    atlas_mode_enabled: Any | None = None
    conversation_origin: str | None = None
    is_read_only: Any | None = None
    voice: str | None = None
    async_status: int | None = None
    disabled_tool_ids: list[Any] | None = None
    is_do_not_remember: bool | None = None
    memory_scope: str | None = None
    context_scopes: Any | None = None
    sugar_item_id: Any | None = None
    sugar_item_visible: bool | None = None
    pinned_time: Any | None = None
    is_study_mode: bool | None = None
    owner: Any | None = None
    id: str | None = None
    mapping: dict[str, Mapping]
