# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-14T10:15:45+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Author(BaseModel):
    role: str


class Content(BaseModel):
    content_type: str
    parts: list[str | dict[str, Any] | None]


class Message(BaseModel):
    author: Author
    content: Content
    create_time: float | None = None


class Mapping(BaseModel):
    message: Message | None = None


class Model(BaseModel):
    title: str | None = None
    conversation_id: str | None = None
    mapping: dict[str, Mapping]
