# generated by datamodel-codegen:
#   filename:  schema_v1_activity_item.json
#   timestamp: 2026-03-14T03:51:52+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class DictItem1(BaseModel):
    label: str
    value: str


class DictItem(BaseModel):
    dict_: list[DictItem1] = Field(..., alias="dict")
    title: str


class LabelValue(BaseModel):
    label: str | None = None
    value: str | None = None
    href: str | None = None
    dict_: list[DictItem] | None = Field(None, alias="dict")
    title: str | None = None


class Model(BaseModel):
    timestamp: int
    media: list[Any]
    label_values: list[LabelValue]
    fbid: str | None = None
