# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-14T18:50:36+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Message(BaseModel):
    id: int
    createdAt: str
    accountType: str
    accountId: int | None = None
    contentType: str
    isPrivate: bool
    senderPlatform: str | None = None
    userAgent: str | None = None


class TextContent(BaseModel):
    body: str


class MessageContentV2(BaseModel):
    content: str


class TextAndReferenceContent(BaseModel):
    text: str | None = None
    referenceType: str
    referenceId: str


class MultipleChoiceOption(BaseModel):
    id: int
    title: str
    selectedAtMs: int | None = None


class MultipleChoicePromptContent(BaseModel):
    promptText: str
    requireResponse: bool
    multipleChoiceOptions: list[MultipleChoiceOption]


class SelectedMultipleChoiceOption(BaseModel):
    id: int
    title: str
    selectedAtMs: int


class MultipleChoiceResponseContent(BaseModel):
    selectedMultipleChoiceOption: SelectedMultipleChoiceOption


class MessageContent(BaseModel):
    textContent: TextContent | None = None
    messageContentV2: MessageContentV2 | None = None
    textAndReferenceContent: TextAndReferenceContent | None = None
    multipleChoicePromptContent: MultipleChoicePromptContent | None = None
    multipleChoiceResponseContent: MultipleChoiceResponseContent | None = None
    bulletinContent: dict[str, Any] | None = None
    eventDescriptionContent: dict[str, Any] | None = None
    msgkitButtonActionStackContent: dict[str, Any] | None = None
    msgkitActionCardContent: dict[str, Any] | None = None
    collapsibleActionStackContent: dict[str, Any] | None = None
    translatedTextContent: dict[str, Any] | None = None


class MessagesAndContent(BaseModel):
    message: Message
    messageContent: MessageContent


class MessageThreadParticipant(BaseModel):
    accountId: int | None = None
    accountType: str
    statusActive: bool
    groupParticipant: bool | None = None
    createdAt: str | None = None
    updatedAt: str | None = None


class MessageThreadUserTag(BaseModel):
    tagName: str
    tagValue: bool


class ReadReceipt(BaseModel):
    messageId: int
    messageReadAt: str


class MessageContentHistory(BaseModel):
    id: int
    messageId: int
    messageThreadId: int
    previousContent: dict[str, Any]


class MessageThread(BaseModel):
    id: int
    messagesAndContents: list[MessagesAndContent]
    messageThreadParticipants: list[MessageThreadParticipant]
    messageThreadUserTags: list[MessageThreadUserTag]
    readReceipts: list[ReadReceipt] | None = None
    messageContentHistories: list[MessageContentHistory] | None = None


class Model(BaseModel):
    messageThreads: list[MessageThread]
