# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    title_name: str = Field(alias="Title Name")
    utc_title_add_date: str = Field(alias="Utc Title Add Date")
    country: str = Field(alias="Country")
