# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-21T18:32:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    Type: str
    Product: str
    Started_Date: str = Field(..., alias="Started Date")
    Completed_Date: str | None = Field(None, alias="Completed Date")
    Description: str
    Amount: str
    Fee: str
    Currency: str
    State: str
    Balance: str | None = None
