# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from pydantic import BaseModel


class Servicedatum(BaseModel):
    searchlocationlatitude: float | None = None
    country: str | None = None
    checkoutdate: str | None = None
    checkindate: str | None = None
    timeofsearch: str
    city: str | None = None
    numberofnights: int
    rawlocation: str | None = None
    numberofguests: int
    searchlocationlongitude: float | None = None
    state: str | None = None


class Model(BaseModel):
    servicedata: list[Servicedatum]
