# generated by datamodel-codegen:
#   filename:  schema_posts.json
#   timestamp: 2026-03-14T14:30:01+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class MediaItem(BaseModel):
    uri: str
    creation_timestamp: int
    media_metadata: dict[str, Any]
    title: str
    cross_post_source: dict[str, Any]


class Model(BaseModel):
    media: list[MediaItem]
