# generated by datamodel-codegen:
#   filename:  schema_stories.json
#   timestamp: 2026-03-14T14:29:52+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class IgStory(BaseModel):
    uri: str
    creation_timestamp: int
    media_metadata: dict[str, Any]
    title: str
    cross_post_source: dict[str, Any]
    dubbing_info: list[Any] | None = None
    media_variants: list[Any] | None = None


class Model(BaseModel):
    ig_stories: list[IgStory]
