# generated by datamodel-codegen:
#   filename:  schema_reels.json
#   timestamp: 2026-03-14T03:30:01+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class MediaItem(BaseModel):
    uri: str
    creation_timestamp: int
    media_metadata: dict[str, Any]
    title: str
    cross_post_source: dict[str, Any]
    dubbing_info: list[Any]
    media_variants: list[Any]


class IgReelsMediaItem(BaseModel):
    media: list[MediaItem]


class Model(BaseModel):
    ig_reels_media: list[IgReelsMediaItem]
