# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    utc_timestamp: str = Field(alias="Utc Timestamp")
    action: str = Field(alias="Action")
    country_iso_code: str = Field("", alias="Country Iso Code")
    device: str = Field("", alias="Device")
    is_kids: str = Field("", alias="Is Kids")
    query_typed: str = Field("", alias="Query Typed")
    displayed_name: str = Field("", alias="Displayed Name")
    section: str = Field("", alias="Section")
