from __future__ import annotations

import json
import logging
from collections.abc import Iterator
from datetime import UTC, datetime

from context_use.batch.grouper import WindowGrouper
from context_use.etl.core.pipe import Pipe
from context_use.etl.core.types import ThreadRow
from context_use.etl.payload.models import (
    CURRENT_THREAD_PAYLOAD_VERSION,
    FibreComment,
    Note,
)
from context_use.memories.config import MemoryConfig
from context_use.memories.prompt.media import MediaMemoryPromptBuilder
from context_use.models.etl_task import EtlTask
from context_use.providers.airbnb.schemas import PROVIDER, AirbnbReviewRecord
from context_use.providers.registry import declare_interaction
from context_use.providers.types import InteractionConfig
from context_use.storage.base import StorageBackend

logger = logging.getLogger(__name__)


class AirbnbReviewsPipe(Pipe[AirbnbReviewRecord]):
    """ETL pipe for Airbnb reviews written by the user.

    Reads ``reviews.json`` and extracts ``reviewsProvided``.
    System-auto-generated reviews and reviews with no comment are skipped.
    """

    provider = PROVIDER
    interaction_type = "airbnb_reviews"
    archive_version = 1
    archive_path_pattern = "*/json/reviews.json"
    record_schema = AirbnbReviewRecord

    def extract_file(
        self,
        source_uri: str,
        storage: StorageBackend,
    ) -> Iterator[AirbnbReviewRecord]:
        raw = storage.read(source_uri)
        data = json.loads(raw)

        for top_level in data:
            for review_wrapper in top_level.get("reviewsProvided", []):
                review = review_wrapper.get("review", {})

                if review.get("isSystemAutoGenerated"):
                    continue

                comment = review.get("comment")
                if not comment or not comment.strip():
                    continue

                submitted_at = review.get("submittedAt")
                if not submitted_at:
                    continue

                yield AirbnbReviewRecord(
                    comment=comment.strip(),
                    rating=review.get("rating", 0),
                    submitted_at=submitted_at,
                    entity_id=review.get("entityId", 0),
                    source=json.dumps(review_wrapper, default=str),
                )

    def transform(
        self,
        record: AirbnbReviewRecord,
        task: EtlTask,
    ) -> ThreadRow:
        published = datetime.fromisoformat(record.submitted_at)
        if published.tzinfo is None:
            published = published.replace(tzinfo=UTC)

        note = Note(  # type: ignore[reportCallIssue]
            content=f"[{record.rating}/5] {record.comment}",
            published=published,
        )

        payload = FibreComment(  # type: ignore[reportCallIssue]
            object=note,
            published=published,
        )

        return ThreadRow(
            unique_key=payload.unique_key(),
            provider=self.provider,
            interaction_type=self.interaction_type,
            preview=payload.get_preview("Airbnb") or "",
            payload=payload.to_dict(),
            version=CURRENT_THREAD_PAYLOAD_VERSION,
            asat=published,
            source=record.source,
        )


declare_interaction(
    InteractionConfig(
        pipe=AirbnbReviewsPipe,
        memory=MemoryConfig(
            prompt_builder=MediaMemoryPromptBuilder,
            grouper=WindowGrouper,
        ),
    )
)
