# generated by datamodel-codegen:
#   filename:  schema_v0.json
#   timestamp: 2026-03-14T03:45:56+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Author(BaseModel):
    value: str


class Time(BaseModel):
    timestamp: int


class StringMapData(BaseModel):
    Author_1: Author = Field(..., alias="Author")
    Time_1: Time = Field(..., alias="Time")


class ImpressionsHistoryPostsSeenItem(BaseModel):
    string_map_data: StringMapData


class Model(BaseModel):
    impressions_history_posts_seen: list[ImpressionsHistoryPostsSeenItem]
