# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-21T18:32:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    Date: str
    Description: str
    Money_Out: str = Field(..., alias="Money Out")
    Money_In: str = Field(..., alias="Money In")
    Balance: str
