# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-13T21:52:42+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ContentItem(BaseModel):
    start_timestamp: str | None
    stop_timestamp: str | None
    flags: Any
    type: str
    text: str | None = None
    citations: list[dict[str, Any]] | None = None
    id: str | None = None
    name: str | None = None
    input: dict[str, Any] | None = None
    message: str | None = None
    integration_name: str | None = None
    integration_icon_url: str | None = None
    icon_name: str | None = None
    context: Any | None = None
    display_content: dict[str, Any] | None = None
    approval_options: list[str] | None = None
    approval_key: str | None = None
    is_mcp_app: Any | None = None
    tool_use_id: str | None = None
    content: list[dict[str, Any]] | None = None
    is_error: bool | None = None
    structured_content: dict[str, Any] | None = None
    meta: Any | None = None
    thinking: str | None = None
    summaries: list[dict[str, Any]] | None = None
    cut_off: bool | None = None
    alternative_display_type: Any | None = None


class ChatMessage(BaseModel):
    uuid: str
    text: str
    content: list[ContentItem]
    sender: str
    created_at: str
    updated_at: str
    attachments: list[dict[str, Any]]
    files: list[dict[str, Any]]


class Model(BaseModel):
    uuid: str
    name: str
    summary: str
    created_at: str
    updated_at: str
    account: dict[str, Any]
    chat_messages: list[ChatMessage]
