# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class WishlistItemDatum(BaseModel):
    pets: int | None = None
    checkIn: str | None = None
    infants: int | None = None
    wishlistItemId: int
    children: int | None = None
    pdpType: str
    adults: int | None = None
    checkOut: str | None = None
    wishlistId: int
    pdpId: str


class WishlistDatum(BaseModel):
    numberOfInfants: int | None = None
    wishlistUserData: list[dict[str, Any]]
    numberOfChildren: int | None = None
    numberOfAdults: int
    numberOfPets: int | None = None
    inviteCode: str
    name: str
    wishlistItemData: list[WishlistItemDatum]
    isPrivate: bool
    wishlistId: int
    wishlistType: str
    checkOutDate: str | None = None
    checkInDate: str | None = None


class Model(BaseModel):
    wishlistData: list[WishlistDatum]
