# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    sent_utc_ts: str = Field(alias="Sent Utc Ts")
    channel: str = Field(alias="Channel")
    title_name: str = Field("", alias="Title Name")
    message_name: str = Field("", alias="Message Name")
    country_iso_code: str = Field("", alias="Country Iso Code")
    device_model: str = Field("", alias="Device Model")
    click_cnt: str = Field("", alias="Click Cnt")
    click_utc_ts: str = Field("", alias="Click Utc Ts")
    link_url: str = Field("", alias="Link Url")
    email_domain_name: str = Field("", alias="Email Domain Name")
    email_locale: str = Field("", alias="Email Locale")
    account_locale: str = Field("", alias="Account Locale")
