# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-21T18:32:40+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    Cardmember: str
    Transaction_Date: str = Field(..., alias="Transaction Date")
    Process_Date: str = Field(..., alias="Process Date")
    Description: str
    Foreign_Spend_Amount: str = Field(..., alias="Foreign Spend Amount")
    Foreign_Spend_Currency: str = Field(..., alias="Foreign Spend Currency")
    Amount: str
    CR: str
