"""TapestryMemory model — stores memory candidates generated by LLM pipelines."""

from __future__ import annotations

from datetime import date

from sqlalchemy import JSON, Date, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from context_use.models.base import Base, TimeStampMixin, _new_uuid


class TapestryMemory(TimeStampMixin, Base):
    """A single memory candidate derived from a day's threads.

    Multiple rows per ``memory_date`` are expected — the LLM may produce
    several candidate memories from one day's worth of content.
    """

    __tablename__ = "tapestry_memories"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=_new_uuid,
    )

    batch_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("batches.id"),
        nullable=False,
        comment="Batch that produced this memory",
    )

    etl_task_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("etl_tasks.id"),
        nullable=False,
        comment="Denormalized for easier querying",
    )

    memory_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="The day this memory covers",
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Generated memory text",
    )

    source_thread_ids: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        comment="Thread UUIDs that contributed to this memory",
    )

    provider: Mapped[str] = mapped_column(String, nullable=False)
    interaction_type: Mapped[str] = mapped_column(String, nullable=False)

    tapestry_id: Mapped[str | None] = mapped_column(
        String(36),
        nullable=True,
        comment="Optional — for aertex compatibility",
    )

    __table_args__ = (
        Index("idx_tapestry_memories_batch_id", "batch_id"),
        Index("idx_tapestry_memories_etl_task_id", "etl_task_id"),
        Index("idx_tapestry_memories_memory_date", "memory_date"),
        Index("idx_tapestry_memories_provider", "provider"),
    )
