# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-14T03:29:56+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Share(BaseModel):
    link: str | None = None
    share_text: str | None = None
    profile_share_username: str | None = None
    profile_share_name: str | None = None
    original_content_owner: str | None = None


class Message(BaseModel):
    sender_name: str
    timestamp_ms: int
    content: str | None = None
    is_geoblocked_for_viewer: bool
    is_unsent_image_by_messenger_kid_parent: bool | None = None
    reactions: list[Any] | None = None
    share: Share | None = None
    photos: list[Any] | None = None
    audio_files: list[Any] | None = None


class Model(BaseModel):
    participants: list[Any]
    messages: list[Message]
    title: str
    is_still_participant: bool
    thread_path: str
    magic_words: list[Any]
