# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-14T14:30:05+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Participant(BaseModel):
    name: str


class Share(BaseModel):
    link: str | None = None
    share_text: str | None = None
    original_content_owner: str | None = None
    profile_share_username: str | None = None
    profile_share_name: str | None = None


class Reaction(BaseModel):
    reaction: str
    actor: str
    timestamp: int | None = None


class Photo(BaseModel):
    uri: str
    creation_timestamp: int


class AudioFile(BaseModel):
    uri: str
    creation_timestamp: int


class Message(BaseModel):
    sender_name: str
    timestamp_ms: int
    content: str | None = None
    is_geoblocked_for_viewer: bool
    is_unsent_image_by_messenger_kid_parent: bool | None = None
    share: Share | None = None
    reactions: list[Reaction] | None = None
    photos: list[Photo] | None = None
    audio_files: list[AudioFile] | None = None


class Model(BaseModel):
    participants: list[Participant]
    messages: list[Message]
    title: str
    is_still_participant: bool
    thread_path: str
    magic_words: list[Any]
