# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-13T22:11:37+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Subtitle(BaseModel):
    name: str
    url: str | None = None


class Model(BaseModel):
    header: str
    title: str
    titleUrl: str | None = None
    time: str
    products: list[str]
    activityControls: list[str] | None = None
    subtitles: list[Subtitle] | None = None
    details: list[dict[str, Any]] | None = None
    locationInfos: list[dict[str, Any]] | None = None
