# generated by datamodel-codegen:
#   filename:  schema_saved_posts.json
#   timestamp: 2026-03-14T03:52:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SavedOn(BaseModel):
    href: str
    timestamp: int | None = None


class StringMapData(BaseModel):
    Saved_on: SavedOn = Field(..., alias="Saved on")


class SavedSavedMediaItem(BaseModel):
    title: str
    string_map_data: StringMapData


class Model(BaseModel):
    saved_saved_media: list[SavedSavedMediaItem]
