# generated by datamodel-codegen:
#   filename:  schema_saved_collections.json
#   timestamp: 2026-03-14T14:29:31+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Name(BaseModel):
    value: str
    href: str | None = None


class CreationTime(BaseModel):
    timestamp: int


class UpdateTime(BaseModel):
    timestamp: int


class AddedTime(BaseModel):
    timestamp: int


class StringMapData(BaseModel):
    Name_1: Name = Field(..., alias="Name")
    Creation_Time: CreationTime | None = Field(None, alias="Creation Time")
    Update_Time: UpdateTime | None = Field(None, alias="Update Time")
    Added_Time: AddedTime | None = Field(None, alias="Added Time")


class SavedSavedCollection(BaseModel):
    title: str | None = None
    string_map_data: StringMapData


class Model(BaseModel):
    saved_saved_collections: list[SavedSavedCollection]
