# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    start_time: str = Field(alias="Start Time")
    duration: str = Field(alias="Duration")
    title: str = Field(alias="Title")
    device_type: str = Field(alias="Device Type")
    country: str = Field(alias="Country")
    attributes: str = Field("", alias="Attributes")
    supplemental_video_type: str = Field("", alias="Supplemental Video Type")
    bookmark: str = Field("", alias="Bookmark")
    latest_bookmark: str = Field("", alias="Latest Bookmark")
