# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    title_name: str = Field(alias="Title Name")
    thumbs_value: str = Field(alias="Thumbs Value")
    rating_type: str = Field(alias="Rating Type")
    event_utc_ts: str = Field(alias="Event Utc Ts")
    star_value: str = Field("", alias="Star Value")
    region_view_date: str = Field("", alias="Region View Date")
    device_model: str = Field("", alias="Device Model")
