# generated by datamodel-codegen:
#   filename:  schema_followers.json
#   timestamp: 2026-03-14T03:29:35+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class StringListDatum(BaseModel):
    href: str
    value: str
    timestamp: int


class Model(BaseModel):
    title: str
    media_list_data: list[Any]
    string_list_data: list[StringListDatum]
