# generated by datamodel-codegen:
#   filename:  schema_following.json
#   timestamp: 2026-03-14T14:29:39+00:00

from __future__ import annotations

from pydantic import BaseModel


class StringListDatum(BaseModel):
    href: str
    timestamp: int


class RelationshipsFollowingItem(BaseModel):
    title: str
    string_list_data: list[StringListDatum]


class Model(BaseModel):
    relationships_following: list[RelationshipsFollowingItem]
