# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Review(BaseModel):
    reviewerId: int
    revieweeRole: str
    isSystemAutoGenerated: bool
    isFamilyFriendly: bool
    hasReviewPeriodExpired: bool
    entityType: str
    rating: int
    isGroupTravel: bool
    firstSubmittedAt: str
    entityId: int
    hasSubmitted: bool
    firstCompletedAt: str
    revieweeId: int
    createdAt: str
    isBusinessTravel: bool
    bookableId: int
    comment: str
    submittedAt: str
    reviewId: int
    commentLanguage: str
    reviewerRole: str
    updatedAt: str


class ReviewsProvidedItem(BaseModel):
    reviewCategoryRatings: list[dict[str, Any]]
    review: Review
    reviewCategoryTags: list[dict[str, Any]]


class Model(BaseModel):
    reviewsProvided: list[ReviewsProvidedItem]
