# generated by datamodel-codegen:
#   filename:  schema_post_comments.json
#   timestamp: 2026-03-14T14:29:19+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Comment(BaseModel):
    value: str


class MediaOwner(BaseModel):
    value: str


class Time(BaseModel):
    timestamp: int


class StringMapData(BaseModel):
    Comment_1: Comment = Field(..., alias="Comment")
    Media_Owner: MediaOwner = Field(..., alias="Media Owner")
    Time_1: Time = Field(..., alias="Time")


class Model(BaseModel):
    media_list_data: list[Any]
    string_map_data: StringMapData
