# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-23T12:54:41+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Text(BaseModel):
    type: str
    text: str


class TextEntity(BaseModel):
    type: str
    text: str


class Message(BaseModel):
    id: int
    type: str
    date: str
    date_unixtime: str
    from_: str | None = Field(None, alias="from")
    from_id: str | None = None
    text: str | list[str | Text]
    text_entities: list[TextEntity]
    forwarded_from: str | None = None
    forwarded_from_id: str | None = None
    photo: str | None = None
    photo_file_size: int | None = None
    width: int | None = None
    height: int | None = None
    file: str | None = None
    file_name: str | None = None
    file_size: int | None = None
    mime_type: str | None = None
    saved_from: str | None = None
    edited: str | None = None
    edited_unixtime: str | None = None
    reply_to_message_id: int | None = None
    media_type: str | None = None
    duration_seconds: int | None = None
    thumbnail: str | None = None
    thumbnail_file_size: int | None = None
    sticker_emoji: str | None = None
    reactions: list[dict[str, Any]] | None = None
    performer: str | None = None
    title: str | None = None
    actor: str | None = None
    actor_id: str | None = None
    action: str | None = None
    emoticon: str | None = None
    inline_bot_buttons: list[list[Any]] | None = None
    poll: dict[str, Any] | None = None
    discard_reason: str | None = None
    location_information: dict[str, Any] | None = None
    live_location_period_seconds: int | None = None
    contact_information: dict[str, Any] | None = None
    inviter: str | None = None
    members: list[str | None] | None = None
    message_id: int | None = None
    via_bot: str | None = None
    game_title: str | None = None
    game_description: str | None = None
    game_link: str | None = None
    game_message_id: int | None = None
    score: int | None = None
    duration: int | None = None
    schedule_date: int | None = None
    invoice_information: str | None = None
    media_spoiler: bool | None = None
    boosts: int | None = None
    contact_vcard: str | None = None
    contact_vcard_file_size: int | None = None
    reply_to_peer_id: str | None = None
    todo_list: dict[str, Any] | None = None
    completed: list[int] | None = None
    incompleted: list[int] | None = None


class Model(BaseModel):
    type: str
    id: int
    messages: list[Message]
    name: str | None = None
