# generated by datamodel-codegen:
#   filename:  schema_story_likes.json
#   timestamp: 2026-03-14T14:29:18+00:00

from __future__ import annotations

from pydantic import BaseModel


class StringListDatum(BaseModel):
    timestamp: int


class StoryActivitiesStoryLike(BaseModel):
    title: str
    string_list_data: list[StringListDatum]


class Model(BaseModel):
    story_activities_story_likes: list[StoryActivitiesStoryLike]
