# generated by datamodel-codegen:
#   filename:  schema_liked_posts.json
#   timestamp: 2026-03-14T03:29:27+00:00

from __future__ import annotations

from pydantic import BaseModel


class StringListDatum(BaseModel):
    href: str
    value: str
    timestamp: int


class LikesMediaLike(BaseModel):
    title: str
    string_list_data: list[StringListDatum]


class Model(BaseModel):
    likes_media_likes: list[LikesMediaLike]
