# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-19T17:16:13+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class LabelValue(BaseModel):
    label: str
    value: str | None = None
    href: str | None = None


class Model(BaseModel):
    timestamp: int
    media: list[Any]
    label_values: list[LabelValue]
    fbid: str
