name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Build
        run: uv build

      - name: Check package
        run: |
          uv run twine check --strict dist/*
          uv run check-wheel-contents dist/
