# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-16T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    profile_name: str = Field(alias="Profile Name")
    show: str = Field(alias="Show")
    is_interested: str = Field(alias="Is Interested")
    event_date: str = Field(alias="Event Date")
    has_watched: str = Field(alias="Has Watched")
